### ISSUE TITLE
internal Server Error RvbdException: Error connecting to appfwk service 'progressd'

### ISSUE THREAD

**Issue by Novatouch** [riverbed/steelscript-appfwk#2]
Hello,

I get this error while trying to run the HTML example report. I performed a fresh install in a virtualenv on a RedHat 6.7 and on a ubuntu 16.04 and get the same results.  Did I miss something during the installation ? 

Start server command: 

`python manage.py runserver 0.0.0.0:8080`

HTTP errors:

```
 [26/May/2016 12:52:29] "POST /report/default/html_example/ HTTP/1.1" 200 810
 [26/May/2016 12:52:30] "POST /report/default/html_example/widgets/weather-image-1-1/jobs/ HTTP/1.1" 400 1800
 [26/May/2016 12:52:30] "POST /report/default/html_example/widgets/report-table-1-7/jobs/ HTTP/1.1" 400 1800
```

Python exceptions: 

```
Traceback (most recent call last):
  File "/opt/steelscript/venv_test/lib/python2.7/site-packages/steelscript/appfwk/apps/report/views.py", line 790, in post
    criteria=form_criteria)
  File "/opt/steelscript/venv_test/lib/python2.7/site-packages/steelscript/appfwk/apps/jobs/models.py", line 323, in create
[pip-freeze.txt](https://github.com/riverbed/steelscript-appfwk/files/284379/pip-freeze.txt)
[pip-freeze.txt](https://github.com/riverbed/steelscript-appfwk/files/284380/pip-freeze.txt)


    master = Job.objects.get_master(handle)
  File "/opt/steelscript/venv_test/lib/python2.7/site-packages/steelscript/appfwk/apps/jobs/models.py", line 109, in get_master
    master_jobs = Task.validate_jobs(jobs=candidates, delete=True)
  File "/opt/steelscript/venv_test/lib/python2.7/site-packages/steelscript/appfwk/apps/jobs/task/async.py", line 59, in validate_jobs
    if validate(j):
  File "/opt/steelscript/venv_test/lib/python2.7/site-packages/steelscript/appfwk/apps/jobs/task/async.py", line 29, in validate
    if not job.done():
  File "/opt/steelscript/venv_test/lib/python2.7/site-packages/steelscript/appfwk/apps/jobs/models.py", line 436, in done
    self.status = int(progressd.get(self.id, 'status'))
  File "/opt/steelscript/venv_test/lib/python2.7/site-packages/steelscript/appfwk/apps/jobs/progress.py", line 35, in get
    r = self._request('GET', '/jobs/items/%d/' % id_)
  File "/opt/steelscript/venv_test/lib/python2.7/site-packages/steelscript/appfwk/apps/jobs/progress.py", line 29, in _request
    "Error connecting to appfwk service 'progressd': "
RvbdException: Error connecting to appfwk service 'progressd': try restarting the service (sudo service progressd restart) or contact your administrator for assistance.
```

pip freeze:

```
APScheduler==3.1.0
Django==1.7.11
Flask==0.10.1
Flask-RESTful==0.3.2
Jinja2==2.8
MarkupSafe==0.23
Werkzeug==0.11.10
amqp==1.4.9
aniso8601==1.1.0
ansi2html==1.1.1
anyjson==0.3.3
billiard==3.3.0.23
celery==3.1.23
django-ace==1.0.2
django-admin-tools==0.5.2
django-celery==3.1.16
django-extensions==1.4.6
django-model-utils==2.0.3
djangorestframework==2.3.13
djangorestframework-csv==1.3.3
funcsigs==1.0.2
futures==3.0.5
importlib==1.0.3
itsdangerous==0.24
jsonfield==0.9.20
kombu==3.0.35
numpy==1.11.0
pandas==0.15.2
pygeoip==0.3.2
python-dateutil==2.5.3
pytz==2016.4
redis==2.10.3
requests==2.4.3
six==1.10.0
steelscript==1.0.1
steelscript.appfwk==1.0
steelscript.netprofiler==1.0.2
steelscript.netshark==1.0
tzlocal==1.2.2
wsgiref==0.1.2
```

steel about:

```
steel about

Installed SteelScript Packages
Core packages:
  steelscript                               1.0.1
  steelscript.netprofiler                   1.0.2
  steelscript.netshark                      1.0

Application Framework packages:
  steelscript.appfwk                        1.0

REST tools and libraries:
  None

Paths to source:
  /opt/steelscript/venv_test/lib/python2.7/site-packages

(add -v or --verbose for further information)
```

**Comment by mgarabed** [comment]
@Novatouch the `progressd` service is provided within the steelscript.appfwk package and can be manually run via the following command:

    $ <virtualenv_dir>/site_packages/steelscript/appfwk/progressd/progressd.py --path <path_to_appfwk_project> --port <port_number_to_use>

You can see the service file template we use in our VM here:

https://github.com/riverbed/steelscript-vm-config/blob/master/provisioning/roles/appfwk_webserver/templates/etc.init.d.progressd.distrib.j2
